# Generated by Django 4.2 on 2025-12-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='item_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
