# Generated by Django 4.2 on 2025-12-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_food_item_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
