# Generated by Django 6.0.2 on 2026-02-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_review_paymentdetail_orderaddress_foodtracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
